{
 "title": "Bee",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "libp2p created connection",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bee_libp2p_created_connection_count{}"
    }
   ]
  },
  {
   "title": "libp2p handled connection",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bee_libp2p_handled_connection_count{}"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - bee_process_start_time_seconds{}"
    }
   ]
  },
  {
   "title": "bee version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "bee_info{}", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "go version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "go_info{}", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "accounting",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_accounting_accounting_blocks_count{}[1m])",
     "legendFormat": "blocks ({{pod}})"
    },
    {
     "expr": "increase(bee_accounting_accounting_disconnects_count{}[1m])",
     "legendFormat": "disconnects ({{pod}})"
    }
   ]
  },
  {
   "title": "events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_accounting_credit_events_count{}[1m])",
     "legendFormat": "credit ({{pod}})"
    },
    {
     "expr": "increase(bee_accounting_debit_events_count{}[1m])",
     "legendFormat": "debit ({{pod}})"
    }
   ]
  },
  {
   "title": "totals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bee_accounting_total_credited_amount{}",
     "legendFormat": "credited ({{pod}})"
    },
    {
     "expr": "bee_accounting_total_debited_amount{}",
     "legendFormat": "debited ({{pod}})"
    }
   ]
  }
 ]
}